project:
  type: website
  output-dir: _site

website:
  title: ""
  favicon: images/tree-favicon.svg
  navbar:
    background: primary
    left:
      - href: problems.qmd
        text: Problems I'm Exploring
      - href: about.qmd
        text: About Me
      - text: Projects
        menu:
          - href: https://true-freelance-ylyl.vercel.app/
            text: True Rate

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
